### ISSUE TITLE
python installation from pyenv not detected when creating venv

### ISSUE THREAD

**Issue by cderv** [pyenv-win/pyenv-win-venv#1]
Hi, 

I am trying to use this project with pyenv-win, but creating the venv does not work as expected

````
$ pyenv versions
* 3.9.13 (set by C:\Users\chris\scoop\apps\pyenv\current\pyenv-win\version)
$ pyenv-venv install 3.9.13 venv39
Python v3.9.13 is not installed. Install using "pyenv install 3.9.13 "
$ pyenv-venv list python
Python Versions installed:
* 3.9.13 (set by C:\Users\chris\scoop\apps\pyenv\current\pyenv-win\version)
````

* pyenv has an install 3.9.13 version
* pyenv-venv sees it when listing python 
* but creating the env says it is not installed somehow. 

I am using pyenv installed through scoop

**Comment by cderv** [comment]
> Is Scoop officially supported? I dont see it in pyenv-win's README

I don't see it either so I asked: https://github.com/pyenv-win/pyenv-win/issues/435

Scoop is quite used on windows for package management, it is good to have pyenv in it. However, it may not be set up correctly (yet) and I am happy to help fix it. 

it seems for example I don't have `PYENV_HOME` set. I have `PYENV` only. 

````
> Get-ChildItem -Path Env: | Where-Object -FilterScript {$_.Name -contains "PYENV"}

Name                           Value
----                           -----
PYENV                          C:\Users\chris\scoop\apps\pyenv\current\pyenv-win
````

So probably Scoop should add the other environment defined here at installation (https://github.com/pyenv-win/pyenv-win#add-system-settings) as you are relying on them, right ?

**Comment by arzkar** [comment]
> So probably Scoop should add the other environment defined here at installation (https://github.com/pyenv-win/pyenv-win#add-system-settings) as you are relying on them, right ?
Yes. It is checking if the given python version exists by looking at `$PYENV_HOME\versions` so it needs that environment variable.
Better to add all the environment variables mentioned in https://github.com/pyenv-win/pyenv-win#add-system-settings
> It just seems 3 times the same path in 3 different env var 
True. No idea why it is that way.

Anyhow, let me know if the issue is fixed after adding all the required environment variables.

**Comment by arzkar** [comment]
Found the reason for the multiple env vars for the same path.
https://github.com/pyenv-win/pyenv-win/pull/313

**Comment by cderv** [comment]
> Yes. It is checking if the given python version exists by looking at $PYENV_HOME\versions so it needs that environment variable.

Ok great. I'll see about that. I was suprised that the python versions was still found by `pyenv-win-venv`

````
 pyenv-venv list python
Python Versions installed:
* 3.9.13 (set by C:\Users\chris\scoop\apps\pyenv\current\pyenv-win\version)
````

There is two mechanisms I guess.

**Comment by arzkar** [comment]
>  I was suprised that the python versions was still found by pyenv-win-venv

It's able to find the python versions because it is just running`pyenv versions` whenever `pyenv-venv list python` is run.

**Comment by cderv** [comment]
Thanks a lot for the help. I'll close this, and fix in Scoop

**Comment by cderv** [comment]
FWIW here is the PR to change scoop installer to have expected env var: https://github.com/ScoopInstaller/Main/pull/3950

**Comment by arzkar** [comment]
Great. That would be very helpful for future Scoop users. 👍

**Comment by GitMurf** [comment]
fyi choco install has the same problem! it only sets the $PYENV env variable and not root or home.
