### ISSUE TITLE
install with path

### ISSUE THREAD

**Issue by szylmzs** [pyenv-win/pyenv-win-venv#18]
how to install a virtual env with specific path but not c:\users\name\.pyenv-win-venv\envs\
i used to put project file and virtual env files both into project directory

**Comment by arzkar** [comment]
It currently doesnt support installing the virtual env in other directories.
>  put project file and virtual env files both into project directory

This will prevent us from reusing a virutal environment in other projects. That is not the aim of this project.
If you want to have virtual env inside your project directory, just use [virtualenv](https://virtualenv.pypa.io/en/latest/) directly, that would be easier and makes more sense for this scenario.
