### ISSUE TITLE
Wrong documentation parameter for pyenv-venv install help page

### ISSUE THREAD

**Issue by cderv** [pyenv-win/pyenv-win-venv#21]
https://github.com/pyenv-win/pyenv-win-venv/blob/1a19780676fdfa5b20a04fa05d64702f374a0da8/bin/pyenv-win-venv.ps1#L359-L368

I think this has currently the same parameter doc than `pyenv-venv list`

**Comment by arzkar** [comment]
Thanks for reporting this.  I have pushed the fix.
