### ISSUE TITLE
pyenv-venv command not found in git bash on Windows

### ISSUE THREAD

**Issue by Fitmavincent** [pyenv-win/pyenv-win-venv#22]
I follow through the installation via Powershell and can confirm the installation is successful. I can bring up the pyenv-venv in powershell. I can also confirm the `pyenv-win-venv\bin` is added to the path. But in my git bash, it does not recognise the command at all.

![Terminal](https://github.com/pyenv-win/pyenv-win-venv/assets/7020812/271d201b-35ad-4080-b4d2-efc130d82b37)

OS: Win10
pyenv: 3.1.1
pyenv-win-venv: 0.6.3

**Comment by arzkar** [comment]
I have pushed a new version which added support for git-bash.
Update the CLI using `pyenv-venv update self`
