### ISSUE TITLE
Git stderr output is not suppressed when updating

### ISSUE THREAD

**Issue by cderv** [pyenv-win/pyenv-win-venv#3]
````
> pyenv-venv update self
fatal: not a git repository (or any of the parent directories): .git
pyenv-win-venv 0.5.0 installed.
New version available: 0.5.2. Updating...
Backing up existing envs to C:\Users\chris\AppData\Local\Temp\pyenv-win-venv-backup-mYyCoTHSLs
Removing C:\Users\chris\.pyenv-win-venv
Restoring Python installations
pyenv-win-venv is successfully installed. You may need to close and reopen your terminal before using it.
````

See first line of results. 

I believe this is because `Out-Null` in powershell only suppresses the stdout, not the stderr. Using complete redirection should be the solution here. Very instructive thread in [SO](https://stackoverflow.com/a/57548278/3436535) about that. 

I'll send a PR.

**Comment by arzkar** [comment]
Yea, I noticed that as well. It was in my backlog but hadn't had the time to fix it. Thanks for the PR.
