### ISSUE TITLE
Feature request: allow usage from `cmd.exe`

### ISSUE THREAD

**Issue by bersbersbers** [pyenv-win/pyenv-win-venv#5]
I usually work in `cmd.exe`, and have to type `powershell pyenv-venv` all the time. What about adding a `pyenv-venv.bat` file that basically does `powershell pyenv-venv %*` or similar?

Edit: `@powershell pyenv-win-venv.ps1 %*` works well.

**Comment by bersbersbers** [comment]
(I just noticed that while most `pyenv-venv` things work via `powershell pyenv-venv`, `powershell pyenv-venv init` does not. Everything works when I run `activate.bat` myself, but then I would not need `pyenv-win-venv`, right?)

**Comment by bersbersbers** [comment]
This doesn't work too bad:

```diff
-- a/bin/pyenv-win-venv.ps1
+++ b/bin/pyenv-win-venv.ps1
@@ -32,7 +32,7 @@ function  main {
                 if (test-path "$cwd\.python-version") {
                     $env_name = (Get-Content "$cwd\.python-version")
                     if ($env_name -And (test-path -PathType container "$app_env_dir\$env_name")) {
-                        &"$app_env_dir\$env_name\Scripts\Activate.ps1"
+                        cmd /k "$app_env_dir\$env_name\Scripts\activate.bat"
                     }
                     exit
                 }
```

**Comment by arzkar** [comment]
Sounds like a good feature. I will add a solution which ensures that the CLI will seamlessly in CMD.

I am on vacation till 9th Oct so expect an update after that.

**Comment by arzkar** [comment]
> `powershell pyenv-venv init` does not. 

It seems to be working fine for me. I have [this](https://github.com/pyenv-win/pyenv-win-venv#env-automatic-activation-using-python-version-file) in my `profile.ps1` so the python env is automatically activated whenever open a terminal in some directory containing the `.python-version` file.
![image](https://user-images.githubusercontent.com/70950611/194772953-4feaf80f-7632-4c2e-891a-89ba175e9de1.png)

**Comment by bersbersbers** [comment]
Sure, the automatic feature works because it is started from within a PowerShell terminal, I guess. I think my approach most closely resembles the manual activation, which I actually prefer. Does `powershell pyenv-venv init` work for you then, without `profile.ps1`? I expect it won't, or maybe I am doing something wrong.

Luckily, the solution may be simple enough by adding a one-file `.bat` file and switching between `Activate.ps1` and `activate.bat`.

**Comment by arzkar** [comment]
> Luckily, the solution may be simple enough by adding a one-file .bat file and switching between Activate.ps1 and activate.bat

I will look into it when I get some time from work. Command Prompt is pretty basic compared to PowerShell so I will need to test if everything works properly. I mostly work with PowerShell and made the CLI with powershell in mind as I am not as well versed with Cmd Prompt as I am with pwsh.
Feel free to push a PR if u already have a working fix for this.

**Comment by bersbersbers** [comment]
Hi, thanks for this. I am still using `pyenv-win` and that's a cool addition. I tested it for 2 minutes and it works fine at a first glance. I will test more, but I can already say I would change this to suppress extra console output:

```diff
diff --git a/bin/pyenv-venv.bat b/bin/pyenv-venv.bat
index ff573c6..7574826 100644
--- a/bin/pyenv-venv.bat
+++ b/bin/pyenv-venv.bat
@@ -1,2 +1,2 @@
 @REM Alias for pyenv-win-venv.bat
-"%USERPROFILE%\.pyenv-win-venv\bin\pyenv-win-venv.bat" %*
\ No newline at end of file
+@"%USERPROFILE%\.pyenv-win-venv\bin\pyenv-win-venv.bat" %*
\ No newline at end of file
diff --git a/bin/pyenv-win-venv.bat b/bin/pyenv-win-venv.bat
index d25e098..9f46c79 100644
--- a/bin/pyenv-win-venv.bat
+++ b/bin/pyenv-win-venv.bat
@@ -1 +1 @@
-powershell -File "%USERPROFILE%\.pyenv-win-venv\bin\pyenv-win-venv.ps1" "bat" %*
\ No newline at end of file
+@powershell -File "%USERPROFILE%\.pyenv-win-venv\bin\pyenv-win-venv.ps1" "bat" %*
\ No newline at end of file
```

(You can also use `@ECHO OFF` at the beginning of a file.)
