### ISSUE TITLE
Installing env using Python v2.7 Error: No module named venv

### ISSUE THREAD

**Issue by a08381** [pyenv-win/pyenv-win-venv#6]
```
PS C:\Users\Administrator\Downloads> pyenv-venv install 2.7.18 global-2
Installing env: global-2 using Python v2.7.18
C:\Users\Administrator\.pyenv\pyenv-win\versions\2.7.18\python.exe: No module named venv
```

**Comment by a08381** [comment]
maybe it still need to use virtualenv module in python 2.7?

**Comment by arzkar** [comment]
Yes. This script is using venv to manage the environments as when I created the tool, I was only using Python 3+. For Python 2, virtualenv needs to be used. I will start working on a fix this weekend.

Feel free to make a PR if this is urgent and you understand what needs to be changed. 
I am busy the whole week so will only be able to work on this on the weekends.
